name: EzMute
version: '${project.version}'
main: me.ezmute.ezmute.EzMute
api-version: 1.18
depend: []
softdepend: []
authors: [ hrdu_ ]
description: Enables players to mute other players
commands:
  mute:
    description: Mutes another player (that's the plan atleast)
    usage: /<command> <player>
